---
apiVersion: v1
kind: Service
metadata:
  name: flaskwebapp-live-service
spec:
  type: LoadBalancer
  selector:
    app: flask-web-app
    version: v1
    color: blue
  ports:
    - name: http
      port: 80
      targetPort: 5000
...
