---
apiVersion: v1
kind: Service
metadata:
  name: flaskwebapp-service
spec:
  type: NodePort
  selector:
    app: flask-web-app
    version: v2
    color: green        
  ports:
    - name: http
      port: 80          
      targetPort: 5000  
      nodePort: 30080   
...
